//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CuentasxCobrar
{
    using System;
    using System.Collections.Generic;

    public class Transaciones
    {
        public int? PageIndex { get; set; }
        public int? PageSize { get; set; }
        public string orderBy0 { get; set; }
        public byte orderByDirection0 { get; set; }


        public int? id_Transaccion { get; set; }
        public string TipoDeMovimiento { get; set; }
        public int? id_TipoDocumento { get; set; }
        public int NumeroDeDocumento { get; set; }
        public string Fecha { get; set; }
        public int? id_Cliente { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }

        public int Linea { get; set; }
        public int Ultima_Linea { get; set; }
        public int Cantidad_Registros { get; set; }
        public string Fecha_Desde { get; set; }
        public string Fecha_Hasta { get; set; }
    }
    public partial class Transaccione
    {
        public int id_Transaccion { get; set; }
        public string TipoDeMovimiento { get; set; }
        public Nullable<int> id_TipoDocumento { get; set; }
        public int NumeroDeDocumento { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> id_Cliente { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
